version: "3.9"

services:
  backend:
    build:
      context: Backend/
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MONGO_URI_L=mongodb+srv://testcrypto:qwerty123
      - MONGO_URI_R=cluster0.eyyi8.mongodb.net/app?retryWrites=true&w=majority
    ports:
      - 8080:8080
    volumes:
     - ./Backend/src:/usr/src/app/src

  frontend:
    build:
      context: Frontend/
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
     - ./Frontend/src:/usr/src/app/src
    stdin_open: true
